App:
  port: 8080

database:
  master_host: localhost
  master_port: 3306
  master_username: root
  master_password: rootpassword
  master_dbname: mydatabase

  replica_host:
  replica_port:
  replica_username:
  replica_password:
  replica_dbname:

  status: false # whether to use replica database or not

redis:
  host: localhost
  port: 6379
  password: kolao@!2025
  db: 0

file:
  host:
  port:
  key:
  bucket:
  path_ip:

api:
  key:

jwt:
  access_token:
  refresh_token: